# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vridge' do
  # Comment the next line if you don't want to use dynamic frameworks

  pod 'Kingfisher', '~>4.7'
  pod 'YPImagePicker'
  pod "TLPhotoPicker"

  use_frameworks!
  # Pods for Vridge

end
